version: 1.0.6

image: Visual Studio 2022

environment:
  PYTHON: C:\Python312-x64\python.exe

install:
  - cmd: "%PYTHON% -m pip install -U pip"
  - cmd: "%PYTHON% -m pip install -r requirements.txt -r requirements-build.txt"

build_script:
  - cmd: "%PYTHON% -m PyInstaller build\flx.spec --clean --noconfirm"
  - ps: Compress-Archive -Path dist\FLX -DestinationPath dist\FLX-Windows.zip -Force

artifacts:
  - path: dist\FLX-Windows.zip
    name: FLX-Windows
