"""FLX Assistant — local Llama via Ollama (script generation + FLX/Fluxer help)."""

from __future__ import annotations

import json
import re
import urllib.error
import urllib.request
from typing import Any

from flx.config import ollama_base_url, ollama_model
from flx.ollama_runtime import (
    ensure_model_ready,
    launch_ollama,
    pull_default_model,
    pull_model_via_api,
    runtime_info,
    wait_for_ollama,
)
from flx.paths import project_root

_CODE_BLOCK_RE = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)
_FLXSCRIPT_NAME_RE = re.compile(r'name\s*=\s*["\']([^"\']+)["\']', re.IGNORECASE)
_BOT_COMMAND_RE = re.compile(
    r'@bot\.command\s*\(\s*name\s*=\s*["\']([a-z][a-z0-9_]*)["\']',
    re.IGNORECASE,
)


def _load_guide_excerpt(max_chars: int = 14_000) -> str:
    path = project_root() / "docs" / "FLXSCRIPT_GUIDE.md"
    if path.is_file():
        return path.read_text(encoding="utf-8")[:max_chars]
    return (
        "FlxScript: use @flxScript, @bot.command, ctx.send, log. "
        "No discord/fluxer imports. Call script_function() at end."
    )


def system_prompt() -> str:
    guide = _load_guide_excerpt()
    return f"""You are **FLX Assistant**, built into the FLX Fluxer selfbot app.

You help users with:
1. **FlxScript** — write complete, runnable Python hub scripts for custom prefix commands.
2. **FLX** — dashboard, Script Hub, built-in commands, config.env, abuse mode, prefixes.
3. **Fluxer** — user-token selfbot context (messages, channels, guilds); not Discord.py.

Rules for scripts:
- Use only `flx.fluxerscript` helpers (`flxScript`, `log`, `getConfigData`, `getScriptsPath`, etc.). Never `import discord` or unofficial Fluxer SDKs.
- Every script needs `@flxScript(...)`, `@bot.command(...)`, and a final `script_function()` call.
- Command names: lowercase letters, numbers, underscore; 2–32 chars.
- Use `<p>` in usage strings for the user's prefix from config.env.
- When the user wants a script, output the **full Python file** in one ```python code fence.
- Outside the fence, briefly explain how to save in Script Hub and run the bot.

**How to send messages (match bundled hub scripts — echo, httpcat, pokemon, check):**
- Use **`ctx.send("...")`** only. Markdown is fine: `**bold**`, newlines, links.
- Do **NOT** use `forwardEmbedMethod`, `ctx.reply_embed`, or fake embed helpers.
- Do **NOT** import `forwardEmbedMethod` in generated scripts.
- Usage errors: `ctx.send("Usage: <p>command <args>")`
- Images/files: `ctx.send("caption")` then `ctx.attach("file.png", data)` when needed (see httpcat/pokemon).
- Guild/API data: `await bot.get_guild_channels(...)` in async handlers, or without await in sync handlers.

Example handler style:
```python
@bot.command(name="hello", description="Say hello")
def hello_cmd(ctx, *, args: str):
    name = args.strip() or "friend"
    ctx.send(f"Hello, **{{name}}**!")
```

FLXSCRIPT REFERENCE (excerpt):
{guide}

Built-in command categories: **general**, **mod** (ban/kick, purge), **abuse** (needs `!abuse` + GUI confirm).
Script Hub has **My scripts** (editable) and **Community** (read-only bundled samples).

If you cannot run tools, still give accurate FLX/Fluxer guidance. Be concise and friendly."""


def extract_python_code(text: str) -> str | None:
    blocks = _CODE_BLOCK_RE.findall(text)
    for block in blocks:
        body = block.strip()
        if "@flxScript" in body or "@bot.command" in body or "flx.fluxerscript" in body:
            return body
    if "@flxScript" in text and "def " in text:
        return text.strip()
    return None


def sanitize_generated_script(code: str) -> str:
    """Strip embed helpers the assistant should not use."""
    if "forwardEmbedMethod" not in code and "reply_embed" not in code:
        return code
    out = code
    for needle in (
        "forwardEmbedMethod,\n",
        "forwardEmbedMethod, ",
        "forwardEmbedMethod\n",
    ):
        out = out.replace(needle, "")
    out = re.sub(
        r"^\s*from flx\.fluxerscript import forwardEmbedMethod\s*\n",
        "",
        out,
        flags=re.MULTILINE,
    )
    out = re.sub(
        r"ctx\.reply_embed\([^)]*\)",
        'ctx.send("…")  # FIXME: replace with your message',
        out,
    )
    return out


def guess_script_meta(code: str) -> dict[str, str]:
    name = "AI Script"
    command = "mycommand"
    m = _FLXSCRIPT_NAME_RE.search(code)
    if m:
        name = m.group(1).strip()
    m = _BOT_COMMAND_RE.search(code)
    if m:
        command = m.group(1).strip().lower()
    desc = f"Generated by FLX Assistant ({command})"
    return {
        "name": name,
        "author": "FLX Assistant",
        "command": command,
        "description": desc,
        "usage": f"<p>{command} <args>",
    }


def ollama_status() -> dict[str, Any]:
    base = ollama_base_url()
    model = ollama_model()
    rt = runtime_info()
    out: dict[str, Any] = {
        "ok": False,
        "base_url": base,
        "model": model,
        "models": [],
        "error": "",
        "bundled": rt.get("bundled_app"),
        "starting": False,
    }
    if not rt.get("api_up"):
        if rt.get("bundled_app") or rt.get("installed_app") or rt.get("cli"):
            out["starting"] = True
            launch_ollama()
            if wait_for_ollama(timeout_sec=8):
                rt = runtime_info()
    try:
        req = urllib.request.Request(f"{base}/api/tags", method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        models = [m.get("name", "") for m in data.get("models") or [] if m.get("name")]
        out["models"] = models
        out["ok"] = True
        if model not in models and models:
            if not any(model in m or m.startswith(model) for m in models):
                if rt.get("bundled_app"):
                    out["warning"] = (
                        f"Downloading {model} in the background (bundled with FLX)…"
                    )
                else:
                    out["warning"] = (
                        f"Model '{model}' not ready yet. Run: ollama pull {model}"
                    )
        elif not models:
            pull_default_model(blocking=False)
            out["warning"] = (
                f"Downloading `{model}` — first run can take a few minutes. "
                f"Or run: ollama pull {model}"
            )
    except urllib.error.URLError as exc:
        if rt.get("bundled_app"):
            out["error"] = "Starting bundled Ollama… try again in a few seconds."
        else:
            out["error"] = (
                f"Cannot reach Ollama at {base}. FLX will install it on first launch "
                f"when bundled; otherwise see https://ollama.com"
            )
        out["detail"] = str(exc.reason or exc)
    except (TimeoutError, json.JSONDecodeError, OSError) as exc:
        out["error"] = str(exc)
    return out


def chat_completion(
    messages: list[dict[str, str]],
    *,
    _retry: bool = False,
    _pulled: bool = False,
) -> dict[str, Any]:
    """Send chat to Ollama. messages: role/content dicts (user/assistant/system)."""
    base = ollama_base_url()
    model = ollama_model()
    if not _pulled:
        ensure_model_ready(blocking=False)
    payload = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {"temperature": 0.35},
    }
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{base}/api/chat",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        err_body = exc.read().decode("utf-8", errors="replace")
        if exc.code == 404 and "not found" in err_body.lower() and not _pulled:
            if pull_model_via_api(model):
                return chat_completion(messages, _retry=_retry, _pulled=True)
            raise RuntimeError(
                f"Downloading `{model}` — first time can take several minutes. "
                f"Keep FLX open or run in Terminal: ollama pull {model}"
            ) from exc
        raise RuntimeError(f"Ollama error ({exc.code}): {err_body[:500]}") from exc
    except urllib.error.URLError as exc:
        if not _retry:
            launch_ollama()
            if wait_for_ollama(timeout_sec=30):
                return chat_completion(messages, _retry=True)
        raise RuntimeError(
            "Ollama is still starting (bundled with FLX on first launch). "
            "Wait a moment and try again."
        ) from exc

    msg = data.get("message") or {}
    content = str(msg.get("content") or "").strip()
    if not content:
        raise RuntimeError("Ollama returned an empty reply.")
    code = extract_python_code(content)
    if code:
        code = sanitize_generated_script(code)
    return {
        "reply": content,
        "script_code": code,
        "script_meta": guess_script_meta(code) if code else None,
    }


def build_messages(
    history: list[dict[str, str]],
    user_message: str,
) -> list[dict[str, str]]:
    out: list[dict[str, str]] = [{"role": "system", "content": system_prompt()}]
    for item in history[-20:]:
        role = str(item.get("role") or "user").strip().lower()
        if role not in ("user", "assistant"):
            continue
        content = str(item.get("content") or "").strip()
        if content:
            out.append({"role": role, "content": content})
    out.append({"role": "user", "content": user_message.strip()})
    return out
